# Project 4: SVM and K-means

UIC CS 412, Spring 2021

*According to the Academic Integrity Policy of this course, all work submitted for grading must be done individually. While we encourage you to talk to your peers and learn from them, this interaction must be superficial with regards to all work submitted for grading. This means you cannot work in teams, you cannot work side-by-side, you cannot submit someone else’s work (partial or complete) as your own. In particular, note that you are guilty of academic dishonesty if you extend or receive any kind of unauthorized assistance. Absolutely no transfer of program code between students is permitted (paper or electronic), and you may not solicit code from family, friends, or online forums. Other examples of academic dishonesty include emailing your program to another student, copying-pasting code from the internet, working in a group on a homework assignment, and allowing a tutor, TA, or another individual to write an answer for you. Academic dishonesty is unacceptable, and penalties range from failure to expulsion from the university; cases are handled via the official student conduct process described at https://dos.uic.edu/conductforstudents.shtml.*

This homework is an individual assignment for all graduate students. Undergraduate students are allowed to work in pairs and submit one homework assignment per pair. There will be no extra credit given to undergraduate students who choose to work alone. The pairs of students who choose to work together and submit one homework assignment together still need to abide by the Academic Integrity Policy and not share or receive help from others (except each other).

There are two parts to this project. The first is on SVM (50%). The second is on k-means (50%). 

## Due Date

This assignment is due at 11:59pm Tuesday, April 13th. 

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Project-4:-SVM-and-K-means" data-toc-modified-id="Project-4:-SVM-and-K-means-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Project 4: SVM and K-means</a></span><ul class="toc-item"><li><span><a href="#Due-Date" data-toc-modified-id="Due-Date-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Due Date</a></span><ul class="toc-item"><li><span><a href="#Files-You'll-Edit" data-toc-modified-id="Files-You'll-Edit-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Files You'll Edit</a></span></li><li><span><a href="#Files-you-might-want-to-look-at" data-toc-modified-id="Files-you-might-want-to-look-at-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Files you might want to look at</a></span></li><li><span><a href="#What-to-Submit" data-toc-modified-id="What-to-Submit-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>What to Submit</a></span><ul class="toc-item"><li><span><a href="#Autograding" data-toc-modified-id="Autograding-1.1.3.1"><span class="toc-item-num">1.1.3.1&nbsp;&nbsp;</span>Autograding</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Part-0:-Autoreload" data-toc-modified-id="Part-0:-Autoreload-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Part 0: Autoreload</a></span></li><li><span><a href="#Part-1:-SVM-[50-points]" data-toc-modified-id="Part-1:-SVM-[50-points]-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Part 1: SVM [50 points]</a></span><ul class="toc-item"><li><span><a href="#WU1-(10-points):" data-toc-modified-id="WU1-(10-points):-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>WU1 (10 points):</a></span></li><li><span><a href="#WU2-(10-points)" data-toc-modified-id="WU2-(10-points)-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>WU2 (10 points)</a></span></li><li><span><a href="#WU3-(10-points):" data-toc-modified-id="WU3-(10-points):-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>WU3 (10 points):</a></span></li><li><span><a href="#WU4-(10-points):" data-toc-modified-id="WU4-(10-points):-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>WU4 (10 points):</a></span></li><li><span><a href="#WU5-(10--points):" data-toc-modified-id="WU5-(10--points):-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>WU5 (10  points):</a></span></li></ul></li><li><span><a href="#Part-3:-K-means-[20-points-implementation,-30-points-written-part]" data-toc-modified-id="Part-3:-K-means-[20-points-implementation,-30-points-written-part]-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Part 3: K-means [20 points implementation, 30 points written part]</a></span><ul class="toc-item"><li><span><a href="#WU6--(10-points)" data-toc-modified-id="WU6--(10-points)-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>WU6  (10 points)</a></span></li><li><span><a href="#WU7-(10-points)" data-toc-modified-id="WU7-(10-points)-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>WU7 (10 points)</a></span></li><li><span><a href="#WU8-(10-points)" data-toc-modified-id="WU8-(10-points)-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>WU8 (10 points)</a></span></li></ul></li></ul></div>

### Files You'll Edit

``clustering.py``: An implementation of k-means that you need to finish.

### Files you might want to look at
  
``svm-train.py``: A wrapper for scikit-learn's SVC class.

``datasets.py``: Where a handful of test data sets are stored.

``util.py``: A handful of useful utility functions: these will
undoubtedly be helpful to you, so take a look!

``drawBoundary.py``: A class for drawing decision boundaries.
    
``data/*``: All of the datasets we'll use.

### What to Submit

You will hand in **all** of the python files listed above as a single zip file **hw4.zip** on 
Gradescope under *Homework 4 - Programming Part*.  The programming part constitutes 20% of the grade for this 
homework. You also need to answer the questions denoted by **WU#** (and a kitten) in this 
notebook which are the other 80% of the homework grade. When you are done, you should 
export **hw4.ipynb** with your answers as a PDF file **hw4WrittenPart.pdf**, upload the 
PDF file to Gradescope under *Homework 4 - Written Part*, and tag each question on Gradescope. 

Your entire homework will be considered late if any of these parts are submitted late. 

The simplest and recommended way to export your python notebook is to select File -> Print Preview (this appears on the notebook, right under the Jupyter logo), then use the browser to print as PDF (e.g., on Chrome this appears under File->Print...->Destination "Save as PDF"). Make sure you double check your final PDF to make sure it's not missing any pieces before submitting your final version!

**After you submit your PDF file, be sure to select the pages for each question or your answer will not be graded**

#### Autograding

Your code will be autograded for technical correctness. Please **do
not** change the names of any provided functions or classes within the
code, or you will wreak havoc on the autograder. We have provided two simple test cases that you can try your code on, see ``run_tests_simple.py``. As usual, you should create more test cases to make sure your code runs correctly.

# Part 0: Autoreload

Before we start, let's import a jupyter notebook extension called [`autoreload`](https://ipython.org/ipython-doc/3/config/extensions/autoreload.html) which would automatically reload changes to external files that you edit.

**If you change something in a file and the changes are not reflected even after an autoreload, you may have to restart your jupyter notebook kernel (Kernel -> Restart).**

A manual alternative to `autoreload` is to reload a particular file using `importlib`.

``import importlib
importlib.reload(dumbClassifiers)``

In [ ]:
%load_ext autoreload
%autoreload 2

# Part 1: SVM [50 points]

Here, we'll play around with SVMs and kernels to get a sense of what they are actually doing. We will use sklearn's SVC library for it.

Let's start by training a simple linear SVM: 

In [ ]:
import svmtrain, drawBoundary, importlib
importlib.reload(svmtrain)

model = svmtrain.SVMWrapper(['-t', '0', '-c', 100, 'data0', 'data0.model'])
model.train()
c = drawBoundary.Boundary('data0')
c.draw()

This invocation of svm-train says:

    -t 0    -- use a linear kernel
    -c 100  -- set "C" = 100, which means "overfit a lot"

This is an easily separable dataset, which is reflected by the small
number of support vectors. In the plot, the SVs are drawn big (and are
on the margin, the dashed line one unit away from the decision
boundary, the solid line).

<img src="kitten.jpeg" width="100px" align="left" float="left"/>
<br><br><br>

## WU1 (10 points):

You should have found that it takes 3 support
vectors. Could you have fewer (eg., 2) support vectors here? Why or why not?

[your WU1 answer here]

Although it's unnecessary, we can also train a polynomial SVM with
degree 10 (for instance), with:

In [ ]:
model = svmtrain.SVMWrapper(['-t', '1', '-r', '1', '-d', 10, '-c', 100, 'data0', 'data0.model'])
model.train()
c = drawBoundary.Boundary('data0')
c.draw()

This says:

    -t 1      -- use a polynomial kernel
    -r 1      -- use (1 + u*v)^degree, where "r" is the "1"
    -d 10     -- tenth degree

You'll see that you get a curved decision boundary, though of course
this is somewhat overkill.

In [ ]:
model = svmtrain.SVMWrapper(['-t', '2', '-c', 100, 'data0', 'data0.model'])
model.train()
c = drawBoundary.Boundary('data0')
c.draw()

(Here, `-t 2` means RBF and `-g 1` means gamma=1)

Again, this is overkill. But we can try to understand RBF kernels a
bit better by "turning up" the gamma:

In [ ]:
model = svmtrain.SVMWrapper(['-t', '2', '-c', 100, '-g', 100, 'data0', 'data0.model'])
model.train()
c = drawBoundary.Boundary('data0')
c.draw()

A gamma of 100 means that you have to be *really* close to a point to
have a kernel value that's non-zero.

<img src="kitten.jpeg" width="100px" align="left" float="left"/>
<br><br><br>

## WU2 (10 points)
(a) Why do you get these little blobs? 

(b) How high do you have to turn gamma up in order to get a little decision boundary around
   each blue example?
   
(c) What is the lowest gamma has to be such that each point is a support vector?

In [ ]:
# [your WU2 code here]

[your WU2 answer here]

Let's now switch to a more complex dataset. We'll begin by failing
with a linear model:

In [ ]:
model = svmtrain.SVMWrapper(['-t', '0', '-c', 100, 'data1', 'data1.model'])
model.train()
c = drawBoundary.Boundary('data1')
c.draw()

As you can see, this data fails horribly.

<img src="kitten.jpeg" width="100px" align="left" float="left"/>
<br><br><br>

## WU3 (10 points): 
There are a lot of red support vectors on the blue side
   of the decision boundary. Why?

[your WU3 answer here]

<img src="kitten.jpeg" width="100px" align="left" float="left"/>
<br><br><br>

## WU4 (10 points):

(a) Using this dataset (data1) train an SVM using a polynomial kernel based on the previous examples. Can you get better mileage out of polynomial kernels on this dataset?

(b) Based on this data and the results using the polynomial kernel, is the 0/1 loss on the training data zero? Is the hinge loss on the training data zero? Why? (note you do not have to compute the exact loss, an explanation is sufficient)

(c) Try different values of "C" for the polynomial kernel. How does the decision boundary change for low values of C and high values of C? Does the 0/1 loss or hinge loss on the training data change at all?

In [ ]:
# [your WU4 code here]

[your WU4 answer here]

<img src="kitten.jpeg" width="100px" align="left" float="left"/>
<br><br><br>

## WU5 (10  points):
Train an RBF kernel on this data. What's the smallest gamma for which you can get a loss of zero on the training data for: 
   
(a) the 0/1 loss 

(b) the hinge loss 


In [ ]:
# [your WU5 code here]

[your WU5 answer here]

# Part 2: K-means [20 points implementation, 30 points written part]

Your second task is to implement the furthest first heuristic for
kmeans clustering in `clustering.py`.

We'll now quickly run through some basic experiments with k-means:

In [ ]:
import clustering, datasets

mu0 = clustering.initialize_clusters(datasets.X2d, 2, 'determ')
(mu,z,obj) = clustering.kmeans(datasets.X2d, mu0)
print(mu)
#array([[ 2.31287961,  1.51333813],
#       [-2.13455999, -2.15661017]])
print(z)
#array([0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
#       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1])
print(obj)
#array([ 1.91484251,  1.91484251])

**Hint:** While running, this will plot the results.  If you want
to turn that off, comment out the obvious line in the `kmeans`
function.  

You can also play with another example:

In [ ]:
mu0 = clustering.initialize_clusters(datasets.X2d2, 4, 'determ')
(mu,z,obj) = clustering.kmeans(datasets.X2d2, mu0)
#Iteration 0, objective=5.84574
#Iteration 1, objective=4.3797
#Iteration 2, objective=3.06938
#Iteration 3, objective=2.45218
#Iteration 4, objective=2.34795
#Iteration 5, objective=2.34795
print(mu)
#array([[ 3.06150611, -1.07977065],
#       [-3.92433223,  1.99052827],
#       [ 0.87252863,  4.63384851],
#       [-3.17087245, -4.10528255]])
print(z)
# a large array
print(obj)
# array([ 5.84574233,  4.37970445,  3.06937814,  2.45218374,  2.34795137,
#        2.34795137])

We can run a test on dispalying digit cluster centers using random initialization:

In [ ]:
import util
importlib.reload(clustering)
from pylab import *

(X,Y) = datasets.loadDigits()
mu0 = clustering.initialize_clusters(X, 10, 'random')
(mu,z,obj) = clustering.kmeans(X, mu0, doPlot=False)
plot(obj)
show(block=False)
util.drawDigits(mu, arange(10))

Once you've implemented the furthest first heuristic (ffh), you can do a test by:

In [ ]:
importlib.reload(clustering)
import numpy as np

finalObj = []
for rep in range(10):
    np.random.seed(1234 + rep)
    mu0 = clustering.initialize_clusters(X, 10, 'ffh')
    (mu,z,obj) = clustering.kmeans(X, mu0, doPlot=False)
    finalObj.append(obj[-1])
#(lots of output)

np.mean(finalObj)
#0.44031610993896342

This may take a few seconds to run. 

Note: we are running kmeans multiple times and taking the mean to provide a way to rougly cross-check your outputs

<img src="kitten.jpeg" width="100px" align="left" float="left"/>
<br><br><br>

## WU6  (10 points)
Run kmeans with ffh. How many iterations does it seem to
take for kmeans to converge using ffh?  Do the resulting cluster means
look like digits for most of these runs?  Pick the "best" run (i.e.,
the one with the lowest final objective) and plot the digits (include
the plot in the writeup).  How many of the digits 0-9 are represented?
Which ones are missing?  Try both with ffh and with random
initialization: how many iterations does it take for kmeans to
converge (on average) for each setting?

In [ ]:
# [your WU6 code here]

[your WU6 answer here]

<img src="kitten.jpeg" width="100px" align="left" float="left"/>
<br><br><br>

## WU7 (10 points)
Repeat WU6, but for k=20.  Pick the best of 5 runs, and
plot the digits.  Are you able to see all digits here?

In [ ]:
# [your WU7 code here]

[your WU7 answer here]

Finally, implement the kmeans++ (km++) heuristic. Here is some output:

In [ ]:
importlib.reload(clustering)

finalObj = []
for rep in range(20):
    np.random.seed(1234 + rep)
    mu0 = clustering.initialize_clusters(X, 10, 'km++')
    (mu,z,obj) = clustering.kmeans(X, mu0, doPlot=False)
    finalObj.append(obj[-1])
#(lots of output)

np.mean(finalObj)
#0.4392510535744174

<img src="kitten.jpeg" width="100px" align="left" float="left"/>
<br><br><br>

## WU8 (10 points)
Compare vanilla kmeans (with random initialization) to ffh to km++ for (a) 
    a small number of clusters (say, 3 or 4) and (b) a large number of clusters (say 20). 
    Do you see a big difference in performance at either end?

In [ ]:
# [your WU8 answer code]

[your WU8 answer here]